name: "Continuous Integration"

on:
  workflow_call:
    inputs:
      php-versions:
        description: "The PHP versions to use when running the job"
        default: '["7.2", "7.3", "7.4", "8.0"]'
        required: false
        type: "string"
      composer-root-version:
        description: "The version the package being tested, in case of circular dependencies."
        required: false
        type: "string"
      unstable-requirement:
        description: "a requirement to test against e.g symfony/framework-bundle 6@dev"
        type: string
        default: ""
        required: false

env:
  fail-fast: true

jobs:
  phpunit:
    name: "PHPUnit"
    runs-on: "ubuntu-20.04"

    strategy:
      matrix:
        php-version: "${{ fromJson(inputs.php-versions) }}"
        dependencies:
          - "highest"
        include:
          - php-version: "${{ fromJson(inputs.php-versions)[0] }}"
            dependencies: "lowest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"
        with:
          fetch-depth: 2

      - name: "Install PHP with PCOV"
        uses: "shivammathur/setup-php@v2"
        if: "${{ matrix.php-version != '7.1' }}"
        with:
          php-version: "${{ matrix.php-version }}"
          coverage: "pcov"
          ini-values: "zend.assertions=1"

      - name: "Install PHP with XDebug"
        uses: "shivammathur/setup-php@v2"
        if: "${{ matrix.php-version == '7.1' }}"
        with:
          php-version: "${{ matrix.php-version }}"
          coverage: "xdebug"
          ini-values: "zend.assertions=1"

      - name: "Set COMPOSER_ROOT_VERSION"
        run: |
          echo "COMPOSER_ROOT_VERSION=${{ inputs.composer-root-version }}" >> $GITHUB_ENV
        if: "${{ inputs.composer-root-version }}"

      - name: "Add unstable requirement"
        run: |
          composer config minimum-stability dev
          composer config prefer-stable true
          composer require ${{ inputs.unstable-requirement }}
        if: "${{ inputs.unstable-requirement != '' }}"

      - name: "Install dependencies with Composer"
        uses: "ramsey/composer-install@v1"
        with:
          dependency-versions: "${{ matrix.dependencies }}"
          composer-options: "--prefer-dist"

      - name: "Run PHPUnit"
        run: "vendor/bin/phpunit --coverage-clover=coverage.xml"

      - name: "Upload coverage file"
        uses: "actions/upload-artifact@v2"
        with:
          name: "phpunit-${{ matrix.php-version }}.coverage"
          path: "coverage.xml"

  upload_coverage:
    name: "Upload coverage to Codecov"
    runs-on: "ubuntu-20.04"
    needs:
      - "phpunit"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"
        with:
          fetch-depth: 2

      - name: "Download coverage files"
        uses: "actions/download-artifact@v2"
        with:
          path: "reports"

      - name: "Upload to Codecov"
        uses: "codecov/codecov-action@v1"
        with:
          directory: "reports"
